name: CI Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**/*'

env: 
  CI: true
      
jobs:
  build-core:
    name: Build, test, and pack Twilio.AspNet.Core
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    # Build and pack Twilio.AspNet.Common
    - name: (Twilio.AspNet.Common) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Common/
      
    - name: (Twilio.AspNet.Common) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Common/
      
    - name: (Twilio.AspNet.Common) Pack
      run: dotnet pack -c Release -o ..\..\
      working-directory: src/Twilio.AspNet.Common/
      
    # Build, test, and pack Twilio.AspNet.Core
    - name: (Twilio.AspNet.Core) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Core/
      
    - name: (Twilio.AspNet.Core) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Core/
     
    - name: (Twilio.AspNet.Core.UnitTests) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Core.UnitTests/
      
    - name: (Twilio.AspNet.Core.UnitTests) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Core.UnitTests/
     
    - name: (Twilio.AspNet.Core.UnitTests) Test
      run: dotnet test --no-build
      working-directory: src/Twilio.AspNet.Core.UnitTests/
      
    - name: (Twilio.AspNet.Core) Pack
      run: dotnet pack -c Release -o ..\..\
      working-directory: src/Twilio.AspNet.Core/
      
  build-mvc:
    name: Build, test, and pack Twilio.AspNet.Mvc
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    # Build and pack Twilio.AspNet.Common
    - name: (Twilio.AspNet.Common) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Common/
      
    - name: (Twilio.AspNet.Common) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Common/
      
    - name: (Twilio.AspNet.Common) Pack
      run: dotnet pack -c Release -o ..\..\
      working-directory: src/Twilio.AspNet.Common/
      
    # Build, test, and pack Twilio.AspNet.Mvc
    - name: (Twilio.AspNet.Mvc) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Mvc/
      
    - name: (Twilio.AspNet.Mvc) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Mvc/
      
    - name: (Twilio.AspNet.Mvc.UnitTests) Restore
      run: dotnet restore
      working-directory: src/Twilio.AspNet.Mvc.UnitTests/
      
    - name: (Twilio.AspNet.Mvc.UnitTests) Build
      run: dotnet build --no-restore
      working-directory: src/Twilio.AspNet.Mvc.UnitTests/
      
    - name: (Twilio.AspNet.Mvc.UnitTests) Test
      run: dotnet test --no-build
      working-directory: src/Twilio.AspNet.Mvc.UnitTests/
      
    - name: (Twilio.AspNet.Mvc) Pack
      run: dotnet pack -c Release -o ..\..\
      working-directory: src/Twilio.AspNet.Mvc/
